-- AllyOS / RenuviaMD — Supabase schema notes  (project: allyos · bjjfedjowjvfkvdpudqw)
-- =============================================================================
-- DO NOT run this file as-is to "create" clinic/provider tables. The provider
-- and clinic model ALREADY EXISTS in this project as `practitioners` and
-- `clinic_accounts` (the AHCA AuditPro / MD-compliance backend). This file is
-- the reconciliation reference: how the AllyOS authoring console maps onto the
-- live tables, plus the only genuinely NEW tables we may add (the clinical
-- library), clearly marked.
--
-- HARD RULE — no patient PHI in Supabase. Patient identity stays on-device in
-- the chairside app. The compliance backend stores at most de-identified visit
-- data (e.g. visits.patient_initials, Visit IDs) under the MD's own privileges,
-- NOT identified charts. See protocols/AUTHORING.md §0.
-- =============================================================================


-- ============================== EXISTING TABLES ==============================
-- (live in project allyos — listed here for reference; DO NOT recreate)
--
-- clinic_accounts   id, legal_name, dba_name, entity_type, ein, service_lines[],
--                   street_address, city, state, zip, county, phone, fax, email,
--                   emr_system, website, md_name, md_license, md_npi, md_email,
--                   md_entity, mdsa_*, provider_mode(APRN_LED|RN_ONLY|HYBRID),
--                   gfe_source(RENUVIA_DIRECT_CARE|IN_HOUSE|EXTERNAL|MIXED),
--                   representations(jsonb), billing_*, active
-- practitioners     id, clinic_id→clinic_accounts, name, position(NP|PA|RN),
--                   license_number, license_expiry, phone, verified_by_md, active
-- clinic_modules    id, clinic_id, module(WELLNESS_IV|MEDSPA|LASER|MOBILE_IV|
--                   GLP_WEIGHT_LOSS|PEPTIDE|BHRT), *_cents, activated_at
-- csv_uploads       id, clinic_id, period, filename, storage_path, status, ...
-- visits            id, clinic_id, csv_upload_id, visit_id, date_of_service,
--                   patient_initials, arnp_name, service_type, protocol_mode,
--                   audit_1..8 (Y/N/NA), custom_1..6 (Y/N/NA), adverse_event_*, ...
-- chart_reviews     id, clinic_id, period, reviewed_by_md, aggregate_*,
--                   status_level(PASS|MONITOR|CORRECTIVE|ESCALATION), status
-- chart_review_visits  id, chart_review_id, visit_id, tier(TIER_0..3),
--                   per_chart_*, findings(jsonb), *_storage_path, md_decision


-- ===================== AUTHORING CONSOLE → LIVE TABLE MAP =====================
-- allyos/authoring.html generates a canonical draft; here is where each lands.
--
-- CLINIC card     -> clinic_accounts
--   name          -> legal_name (+ dba_name)
--   city_state    -> city, state
--   phone         -> phone
--   lines[]       -> service_lines[]  AND one clinic_modules row per line
--                    (iv->WELLNESS_IV, peptides->PEPTIDE, bhrt->BHRT)
--   md_arrangement renuviamd -> md_* keep RenuviaMD defaults; gfe_source as set
--                  own       -> overwrite md_name/md_license/md_npi/md_email
--
-- PROVIDER card   -> practitioners   (the treating NP/PA/RN)
--   name          -> name
--   credential    -> position   (NP/FNP -> NP; PA -> PA; RN/LPN -> RN)
--   state_license -> license_number
--   (the MD of record is NOT a practitioners row — they are the clinic_accounts md_*)
--
--   GAPS to decide (authoring console collects these; live table lacks them):
--     * provider NPI       — practitioners has no npi column
--     * provider email     — practitioners has no email column
--     * MD/DO/FNP position — position enum is NP|PA|RN only
--   Options: (A) map/drop to fit the live table, or (B) ALTER practitioners to
--   add npi/email and widen the enum. Pending your call (see chat).


-- ===================== PROPOSED NEW TABLES (optional) ========================
-- The clinical LIBRARY (ingredients/protocols) does NOT exist in Supabase today;
-- it lives in the repo JSON (protocols/iv-module.json + draft-additions.json),
-- which is version-controlled and 3-auditor-locked. Only create the tables below
-- if you want the library queryable from Supabase too. Until then the repo JSON
-- remains the single source of truth and these stay commented out.

-- create extension if not exists "pgcrypto";
--
-- create table if not exists ingredients (
--   id text primary key,                 -- ING_<SHORTNAME>
--   name text not null unique,
--   status text not null default 'draft' check (status in ('draft','published','locked')),
--   requires_md_signoff boolean not null default true,
--   in_primary_library boolean not null default false,
--   category text[] default '{}', class text, route text, standard text,
--   ceiling text, rate text, absolute_ci text, relative_ci text, guardrail text,
--   monograph jsonb, evidence_grade text, source text, citations text[] default '{}',
--   created_at timestamptz not null default now()
-- );
-- create table if not exists ingredient_screens (
--   id bigint generated always as identity primary key,
--   ingredient_id text not null references ingredients(id) on delete cascade,
--   flag text not null, level text not null check (level in ('avoid','caution')), note text
-- );
-- create table if not exists protocols (
--   id bigint generated always as identity primary key,
--   code text not null unique, title text not null, version text,
--   type text default 'pre-built stack',
--   status text not null default 'draft' check (status in ('draft','locked')),
--   requires_md_signoff boolean not null default true,
--   indication text, scope_limitation text, base text,
--   components jsonb not null default '[]', optional_add_ons jsonb default '[]',
--   infusion_time text, frequency text, key_gates text[] default '{}',
--   evidence_grade text, citations text[] default '{}',
--   in_primary_library boolean not null default false,
--   created_at timestamptz not null default now()
-- );
